//! M2/M3a process-level tests: the `spawn-demo` mode of the node binary
//! launches three CHILD PROCESSES — each holding only its own seed file —
//! and runs the full arc keygen → presign → sign across them (M3a
//! default; `--seeded` keeps the M2 seeded-sign fallback). These tests
//! assert on the demo's RESULT lines; they are the process-separation
//! counterpart of the thread-level `party_mesh` / `party_offline` tests.
//! The M3b tests add `--persist`: durable stores, the transcript/blame
//! archive, and the offline `auditor` subcommand (SPEC §8.6, §A.4).

use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::thread;
use std::time::{Duration, Instant};

use ohm_ecdsa_node::persist::read_transcript;

const BIN: &str = env!("CARGO_BIN_EXE_ohm-ecdsa-node");
const DEMO_TIMEOUT: Duration = Duration::from_secs(180);

/// A fresh empty temp directory for one test.
fn tmpdir(name: &str) -> PathBuf {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.subsec_nanos())
        .unwrap_or(0);
    let dir = std::env::temp_dir().join(format!(
        "ohm-process-test-{name}-{}-{nanos}",
        std::process::id()
    ));
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

/// Run `spawn-demo` with extra args; returns its stdout. Panics (after
/// killing the child) if the demo hangs.
fn run_spawn_demo(extra: &[&str]) -> String {
    let mut child = Command::new(BIN)
        .arg("spawn-demo")
        .args(extra)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn the node binary");
    let deadline = Instant::now() + DEMO_TIMEOUT;
    loop {
        if child.try_wait().expect("poll child").is_some() {
            break;
        }
        if Instant::now() > deadline {
            let _ = child.kill();
            panic!("spawn-demo {extra:?} timed out");
        }
        thread::sleep(Duration::from_millis(50));
    }
    let out = child.wait_with_output().expect("collect output");
    assert!(
        out.status.success(),
        "spawn-demo {extra:?} failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8(out.stdout).expect("utf8 stdout")
}

/// Every process reports the same blame line (via the RESULT summary).
fn assert_blame_line(out: &str, line: &str) {
    for node in ["1", "2", "3"] {
        assert!(
            out.contains(&format!("RESULT blame: node {node} reports \"{line}\"")),
            "stdout:\n{out}"
        );
    }
}

#[test]
fn process_demo_honest_full_arc() {
    // M3a full arc: keygen → presign → sign, all under the key the
    // processes' OWN keygen produced (no ceremony presignature).
    let out = run_spawn_demo(&[]);
    assert!(
        out.contains("RESULT keygen: all 3 processes agree on X"),
        "stdout:\n{out}"
    );
    assert!(
        out.contains("RESULT presign: all 3 processes agree on PRESIG"),
        "stdout:\n{out}"
    );
    assert!(
        out.contains("RESULT sign: all 3 processes agree; signature verifies under X: true"),
        "stdout:\n{out}"
    );
    assert!(out.contains("RESULT demo: SUCCESS"), "stdout:\n{out}");
    assert!(!out.contains("BLAME"), "stdout:\n{out}");
}

#[test]
fn process_demo_tls_full_arc() {
    // M3c: the full arc across 3 child processes over mTLS — per-party
    // self-signed certs generated by spawn-demo, every node pinning the
    // committee set (--tls CERT KEY --pinned DIR). Same guarantees as
    // the plaintext arc; the wire format inside TLS is unchanged.
    let out = run_spawn_demo(&["--tls"]);
    assert!(
        out.contains("mTLS (M3c): TLS 1.3, per-party self-signed certs pinned to the committee"),
        "stdout:\n{out}"
    );
    assert!(
        out.contains("RESULT keygen: all 3 processes agree on X"),
        "stdout:\n{out}"
    );
    assert!(
        out.contains("RESULT presign: all 3 processes agree on PRESIG"),
        "stdout:\n{out}"
    );
    assert!(
        out.contains("RESULT sign: all 3 processes agree; signature verifies under X: true"),
        "stdout:\n{out}"
    );
    assert!(out.contains("RESULT demo: SUCCESS"), "stdout:\n{out}");
    assert!(!out.contains("BLAME"), "stdout:\n{out}");
}

#[test]
fn process_demo_sign_cheater_named_and_signature_delivered() {
    // Node 2's process broadcasts a wrong signature share: the other two
    // PROCESSES both name it, and all three still deliver the signature
    // (§10.4 robust combine).
    let out = run_spawn_demo(&["--cheat-node", "2", "--cheat", "bad-sign-share"]);
    assert_blame_line(&out, "BLAME sign 2");
    assert!(
        out.contains("RESULT sign: all 3 processes agree; signature verifies under X: true"),
        "stdout:\n{out}"
    );
    assert!(out.contains("RESULT demo: SUCCESS"), "stdout:\n{out}");
}

#[test]
fn process_demo_dkg_cheater_named_by_all_via_wire_complaints() {
    // Node 2's process deals a wrong share to party 1: the §6.1 complaint
    // and defense travel between PROCESSES; every process names dealer 2.
    // In the full arc a keygen abort ends the arc — presign and sign are
    // skipped (no key to presign under).
    let out = run_spawn_demo(&["--cheat-node", "2", "--cheat", "bad-deal:1"]);
    assert!(
        out.contains(
            "RESULT keygen: aborted consistently — every process reports \"BLAME keygen 2\""
        ),
        "stdout:\n{out}"
    );
    assert_blame_line(&out, "BLAME keygen 2");
    assert!(
        out.contains("RESULT presign: skipped (keygen aborted)"),
        "stdout:\n{out}"
    );
    assert!(out.contains("RESULT demo: SUCCESS"), "stdout:\n{out}");
}

#[test]
fn process_demo_dkg_cheater_seeded_sign_still_delivers() {
    // The M2 seeded fallback: keygen aborts naming dealer 2, and the
    // (independent, ceremony-seeded) sign phase still delivers.
    let out = run_spawn_demo(&["--seeded", "--cheat-node", "2", "--cheat", "bad-deal:1"]);
    assert!(
        out.contains(
            "RESULT keygen: aborted consistently — every process reports \"BLAME keygen 2\""
        ),
        "stdout:\n{out}"
    );
    assert_blame_line(&out, "BLAME keygen 2");
    assert!(
        out.contains("RESULT sign: all 3 processes agree; signature verifies under X: true"),
        "stdout:\n{out}"
    );
    assert!(out.contains("RESULT demo: SUCCESS"), "stdout:\n{out}");
}

#[test]
fn process_demo_false_accuser_named_by_all() {
    // Node 3's process accuses honest dealer 1: the dealer's defense
    // verifies everywhere, so every process names the accuser.
    let out = run_spawn_demo(&["--cheat-node", "3", "--cheat", "false-accuse:1"]);
    assert!(
        out.contains(
            "RESULT keygen: aborted consistently — every process reports \"BLAME keygen 3\""
        ),
        "stdout:\n{out}"
    );
    assert!(out.contains("RESULT demo: SUCCESS"), "stdout:\n{out}");
}

#[test]
fn process_demo_triples_bad_dleq_named_by_all() {
    // Node 2's process broadcasts an invalid DLEQ product proof in the
    // FIRST triple session of presign (F3): every process names it, and
    // the arc stops before signing.
    let out = run_spawn_demo(&["--cheat-node", "2", "--cheat", "bad-product-proof"]);
    assert!(
        out.contains(
            "RESULT presign: aborted consistently — every process reports \"BLAME triples 2\""
        ),
        "stdout:\n{out}"
    );
    assert_blame_line(&out, "BLAME triples 2");
    assert!(out.contains("RESULT demo: SUCCESS"), "stdout:\n{out}");
}

#[test]
fn process_demo_triples_bad_reshare_named_by_all() {
    // Node 2's process sends a wrong re-shared share to party 1 (F2):
    // the §6.1 complaint/defense rounds travel between PROCESSES inside
    // the triple factory; every process names dealer 2.
    let out = run_spawn_demo(&["--cheat-node", "2", "--cheat", "bad-reshare:1"]);
    assert!(
        out.contains(
            "RESULT presign: aborted consistently — every process reports \"BLAME triples 2\""
        ),
        "stdout:\n{out}"
    );
    assert_blame_line(&out, "BLAME triples 2");
    assert!(out.contains("RESULT demo: SUCCESS"), "stdout:\n{out}");
}

#[test]
fn process_demo_presign_bad_nonce_point_named_by_all() {
    // Node 2's process broadcasts a wrong nonce point R_j (F5): it fails
    // the EvalCom(A[k], 2) check at every process.
    let out = run_spawn_demo(&["--cheat-node", "2", "--cheat", "bad-nonce-point"]);
    assert!(
        out.contains(
            "RESULT presign: aborted consistently — every process reports \"BLAME presign 2\""
        ),
        "stdout:\n{out}"
    );
    assert_blame_line(&out, "BLAME presign 2");
    assert!(out.contains("RESULT demo: SUCCESS"), "stdout:\n{out}");
}

#[test]
fn process_demo_presign_bad_open_share_named_by_all() {
    // Node 2's process broadcasts a wrong v opening share: it fails the
    // point-equality opening check at every process (fail-fast, §4.6).
    let out = run_spawn_demo(&["--cheat-node", "2", "--cheat", "bad-open-share"]);
    assert!(
        out.contains(
            "RESULT presign: aborted consistently — every process reports \"BLAME presign 2\""
        ),
        "stdout:\n{out}"
    );
    assert_blame_line(&out, "BLAME presign 2");
    assert!(out.contains("RESULT demo: SUCCESS"), "stdout:\n{out}");
}

/// Run the `auditor` subcommand; returns (exit-ok, stdout).
fn run_auditor(token: &std::path::Path, committee: &std::path::Path) -> (bool, String) {
    let out = Command::new(BIN)
        .arg("auditor")
        .arg(token)
        .arg(committee)
        .output()
        .expect("spawn the auditor");
    (
        out.status.success(),
        String::from_utf8(out.stdout).expect("utf8 stdout"),
    )
}

#[test]
fn process_demo_persist_full_arc() {
    // M3b: the full arc with `--persist` — every process runs with a
    // per-node --data-dir. The signature is delivered; afterwards each
    // node's store shows the fsync'd consume tombstone (the `.presig`
    // file is gone, §8.6) and each node's transcript archive decodes.
    let dir = tmpdir("persist-arc");
    let out = run_spawn_demo(&["--dir", dir.to_str().unwrap(), "--persist"]);
    assert!(out.contains("RESULT demo: SUCCESS"), "stdout:\n{out}");
    for id in 1..=3usize {
        let store = dir.join(format!("node-{id}/store"));
        assert!(store.join("0.consumed").exists(), "node {id} tombstone");
        assert!(!store.join("0.presig").exists(), "node {id} live record");
        let transcript = dir.join(format!("node-{id}/archive/transcript.log"));
        let entries = read_transcript(&transcript).unwrap();
        assert!(!entries.is_empty(), "node {id} transcript");
    }
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn process_demo_auditor_verifies_and_rejects_token() {
    // M3b, SPEC §A.4: node 2's process deals a wrong share to party 1 in
    // keygen; every process names dealer 2, and the accuser's process
    // archives a blame-token file. The offline auditor verifies it
    // (exit 0, VERDICT: VALID) and rejects a tampered copy (exit 1).
    let dir = tmpdir("auditor");
    let out = run_spawn_demo(&[
        "--dir",
        dir.to_str().unwrap(),
        "--persist",
        "--cheat-node",
        "2",
        "--cheat",
        "bad-deal:1",
    ]);
    assert_blame_line(&out, "BLAME keygen 2");
    let token = dir.join("node-1/archive/blame-keygen-2.tok");
    assert!(token.exists());
    let committee = dir.join("committee.hex");
    let (ok, stdout) = run_auditor(&token, &committee);
    assert!(ok, "auditor rejected the honest token:\n{stdout}");
    assert!(stdout.contains("VERDICT: VALID"), "stdout:\n{stdout}");
    // Flip one byte: the auditor must reject.
    let mut bytes = std::fs::read(&token).unwrap();
    let mid = bytes.len() / 2;
    bytes[mid] ^= 0x01;
    let tampered = dir.join("tampered.tok");
    std::fs::write(&tampered, &bytes).unwrap();
    let (ok, stdout) = run_auditor(&tampered, &committee);
    assert!(!ok, "auditor accepted a tampered token:\n{stdout}");
    assert!(stdout.contains("VERDICT: INVALID"), "stdout:\n{stdout}");
    std::fs::remove_dir_all(&dir).ok();
}
